export const notesData = [
    {
      id: 1,
      name: 'Shopping list',
      createTime: '2023-07-24 ',
      content: 'Some content',
      category: 'Random Thought',
      dates: [],
      archived: false,
    },
    {
      id: 2,
      name: 'The theory of evolut',
      createTime: '2023-07-25 ',
      content: 'some content',
      category: 'Random Thought',
      dates: [],
      archived: true,
    },
    {
        id: 3,
        name: 'New Feature',
        createTime: '2023-07-26 ',
        content: 'some content',
        category: 'Idea',
        dates: [], 
        archived: false,
      },
      {
        id: 4,
        name: 'Wiliam Gaddis',
        createTime: '2023-07-26 ',
        content: 'some content',
        category: 'Quote',
        dates: [],
        archived: false,
      },
      {
        id: 5,
        name: 'Books',
        createTime: '2023-07-27 ',
        content: 'some content',
        category: 'Task',
        dates: [], 
        archived: false,
      },
      {
        id: 6,
        name: 'Computers',
        createTime: '2023-07-27 ',
        content: 'some content',
        category: 'Idea',
        dates: [],
        archived: false,
      },
      {
        id: 7,
        name: 'Language',
        createTime: '2023-07-27 ',
        content: 'Learn JavaScript',
        category: 'Task',
        dates: [],
        archived: false,
      },
      
  ];